jina_api_key=""
jina_reader_concurrency=4

[providers.openrouter]
base_url="https://openrouter.ai/api/v1"
api_key=""

[llm_configs."gemini-2.5-flash"]
provider="openrouter"
model_name="google/gemini-2.5-flash"

[llm_configs."gemini-2.5-pro"]
provider="openrouter"
model_name="google/gemini-2.5-pro"

[llm_configs."gemini-2.5-flash-lite"]
provider="openrouter"
model_name="google/gemini-2.5-flash-lite-preview-06-17"

[engine_configs.pardo-pro]
engine="pardo"
translate_model_name="gemini-2.5-flash"
single_qa_model_name="gemini-2.5-pro"
summary_qa_model_name="gemini-2.5-flash"


[engine_configs.pardo]
engine="pardo"
translate_model_name="gemini-2.5-flash"
single_qa_model_name="gemini-2.5-flash"
summary_qa_model_name="gemini-2.5-flash"

[engine_configs.villv]
engine="villv"
translate_model_name="gemini-2.5-flash"
split_model_name="gemini-2.5-flash"
qa_model_name="gemini-2.5-flash"
summary_model_name="gemini-2.5-flash"
recursive_splitting=false

[engine_configs.villv-pro]
engine="villv"
translate_model_name="gemini-2.5-flash"
split_model_name="gemini-2.5-flash"
qa_model_name="gemini-2.5-flash"
summary_model_name="gemini-2.5-flash"
recursive_splitting=true