jina_api_key=""
jina_reader_concurrency=3

[providers.openrouter]
base_url="https://openrouter.ai/api/v1"
api_key=""

[[llm_models]]
provider="openrouter"
name="google/gemini-2.5-flash"

[[llm_models]]
provider="openrouter"
name="google/gemini-2.5-pro"

[[llm_models]]
provider="openrouter"
name="google/gemini-2.5-flash-lite-preview-06-17"

[[llm_models]]
provider="openrouter"
name="perplexity/sonar-reasoning-pro"

[engine_configs.pardo]
translate_model_name="google/gemini-2.5-flash-lite-preview-06-17"
single_qa_model_name="google/gemini-2.5-pro"
summary_qa_model_name="google/gemini-2.5-flash"